#!/usr/bin/env Rscript

# Authors: Rebekka Mueller, David Widmann
# 2016-12-23
# v0.1

"Cluster AneuFinder models by quality.

Usage:
  clusterbyquality.R [options] <model>...
  clusterbyquality.R -h | --help
  clusterbyquality.R --version

Arguments:
  <model>                AneuFinder model (DNAcopy or HMM).

Options:
  -h, --help             Show this screen.
  --version              Show version.
  -e, --ellipses         Add ellipses with axes corresponding to the within-cluster covariances to plot.
  -f, --force            Force to overwrite the output files if present.
  -o, --output <output>  Output prefix [default: ./clusterbyquality].
" -> doc

suppressPackageStartupMessages(library(docopt))

opt <- docopt(doc, version="0.1")

cat("Options:\n")
cat("\tmodel =", opt$model, "\n")
cat("\tellipses = ", opt$ellipses, "\n")
cat("\tforce =", opt$force, "\n")
cat("\toutput =", opt$output, "\n\n")

# Set up output directory
if (!dir.exists(dirname(opt$output)))
  dir.create(dirname(opt$output), recursive=TRUE)

if (!opt$force && any(file.exists(paste0(opt$output, c('.pdf', '.RData')))))
  stop("Output file already exists. Specify '-f' or '--force' on the commandline to overwrite it.")

# Load AneuFinder
cat("Loading AneuFinder ...\n\n")
suppressPackageStartupMessages(library(AneuFinder))
suppressPackageStartupMessages(library(mclust))

# Load AneuFinder models
models <- loadFromFiles(opt$model, check.class='aneuHMM')

# Set quality measures depending on type of models
models.method <- sapply(models, function (x) {
                          match.call(definition = findCNVs <- function(method, ...) {},
                                     attr(x, "call"))$method})
if (any(models.method=="dnacopy")) {
  measures <- c('spikiness','num.segments','entropy','sos')
  cat("Found AneuFinder model generated by DNAcopy.\n")
} else {
  measures <- c('spikiness','num.segments','entropy','bhattacharyya','sos')
}
cat("Using quality measures ", toString(measures), ".\n\n", sep="")

# Cluster selected HMM files
cl <- clusterByQuality(models, measures=measures)

cat("Found", length(cl$classification), "clusters with the following parameters:\n")
print(cl$parameters)
cat("\n")

# Plot clusters
plot.filename <- paste0(opt$output, '.pdf')
cat("Plotting clusters to", plot.filename, "...\n")
pdf(file = plot.filename, width = 7, height = 7)
plot(cl$Mclust, what='classification', addEllipses=opt$ellipses)
legend(x = "bottom", legend=seq_along(cl$classification), xpd=TRUE, horiz=TRUE,
       inset=c(0,-0.03), bty='n', pch=mclust.options("classPlotSymbols"),
       col=mclust.options("classPlotColors"))
invisible(dev.off())

# Save classification
cluster.filename <- paste0(opt$output, '.RData')
cat("Saving clusters to", cluster.filename, "...\n")
save(cl, file = cluster.filename)

cat("\nDone.\n")
